tags:
  - name: anuncios
    description: anuncios API

paths:
  # [GET] anuncios
  /api/anuncios:
    get:
      tags:
        - anuncios
      summary: Find All Anuncios
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Busca solo los anuncios que inicien con esos datos
        - in: query
          name: sell
          schema:
            type: boolean
          description: true para buscar anuncios en venta o false para buscar anuncios de busqueda
        - in: query
          name: tags
          schema:
            type: array
            collectionFormat: multi
            items:
              type: srting
              enum: [motor, mobile]
          description: Busca solo los anuncios que posean los tags seleccionados, los tags validos son motor, mobile, lifestyle, work
        - in: query
          name: price
          schema:
            type: number
          description: Busca solo los anuncios que coincidan con el precio
        - in: query
          name: priceMax
          schema:
            type: number
          description: Filtra los anuncios hasta un maximo de precio
        - in: query
          name: priceMin
          schema:
            type: number
          description: Filtra los anuncios desde un minimo de precio
        - in: query
          name: skip
          schema:
            type: number
          description: Salta la cantidad de anuncios indicada
        - in: query
          name: limit
          schema:
            type: number
          description: Nos limita la cantidad de anuncios a buscar
        - in: query
          name: select
          schema:
            type: string
          description: Selecciona los datos que queremos de los anuncios
        - in: query
          name: sort
          schema:
            type: string
          description: Oredena los anuncios segun el parametro que queramos
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

    # [POST] anuncios
    post:
      tags:
        - anuncios
      summary: Add anuncios
      parameters:
        - name: body
          in: body
          description: Anuncio Data
          required: true
          schema:
            $ref: "#/definitions/anuncios"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] anuncios/id
  /anuncios/{id}:
    get:
      tags:
        - anuncios
      summary: Find Anuncio By Id
      parameters:
        - name: id
          in: path
          description: Anuncio Id
          required: true
          type: integer
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] anuncios/id
    put:
      tags:
        - anuncios
      summary: Update Anuncio By Id
      parameters:
        - name: id
          in: path
          description: anuncio Id
          required: true
          type: integer
        - name: body
          in: body
          description: anuncio Data
          required: true
          schema:
            $ref: "#/definitions/anuncios"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] anuncios/id
    delete:
      tags:
        - anuncios
      summary: Delete Anuncio By Id
      parameters:
        - name: id
          in: path
          description: anuncio Id
          required: true
          type: integer
      responses:
        200:
          description: "OK"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

# definitions
definitions:
  anuncios:
    type: object
    required:
      - name
      - price
      - sell
      - tags
      - photo
    properties:
      name:
        type: string
        description: Nombre del articulo
      price:
        type: number
        description: Precio del articulo debe ser mayor a cero
      sell:
        type: boolean
        description: Indica si el anuncio es para vender o para buscar un articulo, true para vender y false para buscar
      tags:
        type: string
        description: Tags asociados al articulo. Tags validos son work, motor, mobile, lifestyle
      photo:
        type: string
        description: Direccion de la foto del articulo

schemes:
  - https
  - http
